name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby Gems
        uses: ruby/setup-ruby@v1
        with:
          # ruby version is set via '.ruby-version' file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
